#### Membership
protocol.membership.sampletime 1000
protocol.membership.samplesize 8
#### Channel metrics on Membership
protocol_metrics_interval -1
channel_metrics_interval -1

#### Dissemination
fanout=6

#### App
app.payload.size 20
app.broadcast.period 3000
app.op.folder /home/distalg13/operations
#app.op.folder ./operations
app.op.start.file go.flag
app.of.fail.file fail.flag
app.op.file.pool 1000
